title: Google Analytics Demos & Tools
host: ga-dev-tools.appspot.com
slug: ''
path: '/'
tracking_id: UA-41425441-5
tracking_id_testing: UA-41425441-7
client_id: 793177639245-olst43lspv93vkoql0b9l26hmpf9kfmv.apps.googleusercontent.com


projects:
- title: Account Explorer
  type: tool
  slug: account-explorer
  tech: [embed_api, management_api]
- title: Embed API
  type: demo
  slug: embed-api
  pages:
  - title: Overview
    slug: overview
    tech: [embed_api]
  - title: Tutorials
    slug: tutorials
    tech: [embed_api]
  - title: Interactive Charts
    slug: interactive-charts
    tech: [embed_api]
  - title: Working with Custom Components
    slug: custom-components
    tech: [embed_api]
  - title: Comparison
    slug: comparison
    tech: [embed_api, real_time_reporting_api]
- title: Hit Builder
  type: tool
  slug: hit-builder
  tech: [measurement_protocol_validation_server]
- title: Polymer Elements
  type: demo
  slug: polymer-elements
  tech: [management_api, metadata_api]
  external:
    action: View Demo
    url: https://elements.polymer-project.org/elements/google-analytics?view=demo:demo/index.html
- title: Query Explorer
  type: tool
  slug: query-explorer
  tech: [core_reporting_api, embed_api, management_api, metadata_api]

# Google Analytics tech tags. Demos and tools should tag themselves with
# one or more of these to make tech more discoverable.
tech:
  analyticsjs:
    name: analytics.js
    url: https://developers.google.com/analytics/devguides/collection/analyticsjs/
  autotrack:
    name: autotrack
    url: https://github.com/googleanalytics/autotrack/
  core_reporting_api:
    name: Core Reporting API
    url: https://developers.google.com/analytics/devguides/reporting/core/
  ecjs:
    name: Enhanced Ecommerce (ec.js)
    url: https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce
  embed_api:
    name: Embed API
    url: https://developers.google.com/analytics/devguides/reporting/embed/
  management_api:
    name: Management API
    url: https://developers.google.com/analytics/devguides/config/mgmt/
  mcf_reporting_api:
    name: MCF Reporting API
    url: https://developers.google.com/analytics/devguides/reporting/mcf/
  measurement_protocol:
    name: Measurement Protocol
    url: https://developers.google.com/analytics/devguides/collection/protocol/
  measurement_protocol_validation_server:
    name: Measurement Protocol Validation Server
    url: https://developers.google.com/analytics/devguides/collection/protocol/v1/validating-hits
  metadata_api:
    name: Metadata API
    url: https://developers.google.com/analytics/devguides/reporting/metadata/
  provisioning_api:
    name: Provisioning API
    url: https://developers.google.com/analytics/devguides/config/provisioning/
  real_time_reporting_api:
    name: Real Time Reporting API
    url: https://developers.google.com/analytics/devguides/reporting/realtime/
  api_client_library_python:
    name: Google API Client Library for Python
    url: https://developers.google.com/api-client-library/python/start/installation
  tag_assistant:
    name: Tag Assistant
    url: https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk


# Links represent external URLs that may change.
# Setting them here makes it easier to update globally.
links:
  devsite: http://developers.google.com/analytics
  github: https://github.com/googleanalytics/ga-dev-tools